name: washed_clean
description: A Flutter app that helps users clean and maintain clothes via search, camera-based label reading, and educational content.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Storage
  shared_preferences: ^2.2.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  
  # UI & Content
  flutter_markdown: ^0.6.18+2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Camera & Vision
  camera: ^0.10.5+5
  permission_handler: ^11.1.0
  
  # Search
  collection: ^1.18.0
  
  # External Links
  url_launcher: ^6.2.2
  
  # Analytics & Ads
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  google_mobile_ads: ^4.0.0
  
  # Localization
  intl: ^0.20.2
  
  # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/seed/
    - assets/symbols/
  
  fonts:
    - family: Cocogoose
      fonts:
        - asset: assets/fonts/Cocogoose-Regular.ttf
        - asset: assets/fonts/Cocogoose-Bold.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.ttf
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Bold.ttf
          weight: 700
