// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBThXYvgcspcTsPZmqPLYCYD22ivHILoEY',
    appId: '1:10752647639:android:509797a10593cb97bceb92',
    messagingSenderId: '10752647639',
    projectId: 'washedclean-2a45d',
    storageBucket: 'washedclean-2a45d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBruwQ5HYWyjOM5hqoEX2Kv-IkfUXTUdb0',
    appId: '1:10752647639:web:012ede9e0394ffc2bceb92',
    messagingSenderId: '10752647639',
    projectId: 'washedclean-2a45d',
    authDomain: 'washedclean-2a45d.firebaseapp.com',
    storageBucket: 'washedclean-2a45d.firebasestorage.app',
    measurementId: 'G-11P0M5P9SZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZoHgthNWEYEI6h90sA0sZ3k0bkWqo6U',
    appId: '1:10752647639:ios:f55ce693cf06dac8bceb92',
    messagingSenderId: '10752647639',
    projectId: 'washedclean-2a45d',
    storageBucket: 'washedclean-2a45d.firebasestorage.app',
    iosBundleId: 'com.washedclean.app',
  );

}